### ISSUE TITLE
Spotify error

### ISSUE THREAD

**Issue by Tduck5819** [distubejs/spotify#19]
when i want to play a playlist i wil get this error

Musica > TypeError [PlayError]: *******                                                      
xx Musica > Cannot read properties of undefined (reading '0')                                                                                                        
xx Musica >     at SpotifyPlugin.play (/home/tijmen/musica/node_modules/@distube/spotify/dist/index.js:183:36)                                                  
xx Musica >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                        
xx Musica >     at async DisTube.play (/home/tijmen/musica/node_modules/distube/dist/index.js:2264:13)

**Comment by skick1234** [comment]
Update it. Fixed 4h ago

**Comment by Tduck5819** [comment]
updated to 1.4.4 but stil get error's 

TypeError [PlayError]: https://open.spotify.com/playlist/4zDpUOC91nG4jd4XKkNjr7?si=jCDEV8AUTT2lkqK59iRnYg&utm_source=copy-link
Cannot read properties of undefined (reading 'spotify')
    at SpotifyPlugin.play (/home/tijmen/musicadev/node_modules/@distube/spotify/dist/index.js:237:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DisTube.play (/home/tijmen/musicadev/node_modules/distube/dist/index.js:2264:13)

**Comment by Corentin28** [comment]
I got the same error :

`PlayError: https://open.spotify.com/playlist/6UEwaRtOTaWnxu5Q2Q0azJ?si=6be3b59b7eb34853
Cannot read properties of undefined (reading 'spotify')
    at SpotifyPlugin.play (C:\Users\Quentin\OneDrive\Documents\MomBOT\MomBOT™\node_modules\@distube\spotify\dist\index.js:239:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DisTube.play (C:\Users\Quentin\OneDrive\Documents\MomBOT\MomBOT™\node_modules\distube\dist\index.js:2264:13)
    at async Object.execute (C:\Users\Quentin\OneDrive\Documents\MomBOT\MomBOT™\Commandes\Utilitaires\subCommands\play.js:20:9)`

**Comment by skick1234** [comment]
Hmm, external_urls doesn't change in my region. I will test with vpn and fix it soon

**Comment by skick1234** [comment]
Fixed with https://github.com/distubejs/spotify/commit/ecbdc64238a3704965e929e8aeedaf19e2271df2
