### ISSUE TITLE
Distube spotify plugin problem.

### ISSUE THREAD

**Issue by brendonlock** [distubejs/spotify#9]
I copied the documentation on npmjs.com and i get an error:

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\Brendon\Desktop\kream-testing\node_modules\@distube\spotify\index.js:6:46)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Brendon\Desktop\kream-testing\index.js:64:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by skick1234** [comment]
![image](https://user-images.githubusercontent.com/11555687/126872115-1dc72534-03f0-4f19-a49e-fed06f6cacf9.png)
